version: '2.2'

services:
    ceph-base:
        image: ${CEPH_IMAGE:-rhcsdashboard/ceph-rpm:master}
        volumes:
            - ./docker/ceph:/docker:z
            - ${CEPH_REPO_DIR}:/ceph
            - ${CEPH_CUSTOM_BUILD_DIR:-empty_volume}:/build
            - ${HOST_CCACHE_DIR:-~/.ccache}:/root/.ccache
        environment:
            - ALERTMANAGER_HOST_PORT=${ALERTMANAGER_HOST_PORT}
            - CEPH_DEBUG=${CEPH_DEBUG:-0}
            - CEPH_PORT=10000
            - CEPH_REPO_DIR
            - CHECK_MYPY=${CHECK_MYPY:-0}
            - CYPRESS_CACHE_FOLDER=/ceph/build.cypress
            - DASHBOARD_DEV_SERVER=${DASHBOARD_DEV_SERVER:-1}
            - DASHBOARD_SSL=${DASHBOARD_SSL:-0}
            - FS
            - GRAFANA_HOST_PORT=${GRAFANA_HOST_PORT}
            - MDS
            - MGR
            - MON
            - MON_MAX_PG_PER_OSD
            - NFS
            - NG_CLI_ANALYTICS=false
            - NODE_EXPORTER_HOST_PORT=${NODE_EXPORTER_HOST_PORT}
            - OSD
            - PROMETHEUS_HOST_PORT=${PROMETHEUS_HOST_PORT}
            - PYTHONDONTWRITEBYTECODE=1
            - REMOTE_DASHBOARD_URL
            - RGW
            - RGW_MULTISITE=${RGW_MULTISITE:-0}
        cap_add:
            - ALL
        entrypoint: /docker/entrypoint.sh
        command: /docker/start.sh
        scale: -1
    ceph:
        extends:
            service: ceph-base
        container_name: ceph
        hostname: ceph
        ports: ['${CEPH_PROXY_HOST_PORT:-4200}:4200','${CEPH_HOST_PORT:-11000}:11000']
        scale: 1

    ceph-cluster2:
        extends:
            service: ceph-base
        container_name: ceph-cluster2
        hostname: ceph-cluster2

    ceph-host2:
        extends:
            service: ceph-base
        container_name: ceph-host2
        hostname: ceph-host2
        command: /docker/start-ceph-additional-host.sh

    ceph2:
        extends:
            service: ceph-base
        image: ${CEPH2_IMAGE:-rhcsdashboard/ceph-rpm:master}
        container_name: ceph2
        hostname: ceph2
        ports: ['${CEPH2_PROXY_HOST_PORT:-4202}:4200','${CEPH2_HOST_PORT:-11002}:11000']
        volumes:
            - ${CEPH2_REPO_DIR}:/ceph
            - ${CEPH2_CUSTOM_BUILD_DIR:-empty_volume}:/build

    grafana:
        image: ${GRAFANA_IMAGE:-grafana/grafana:5.4.3}
        container_name: grafana
        hostname: grafana
        ports: ['${GRAFANA_HOST_PORT:-3000}:3000']
        volumes:
            - grafana_data:/var/lib/grafana
            - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini:Z
            - ./docker/grafana/provisioning:/etc/grafana/provisioning:Z
            - ${CEPH_REPO_DIR}/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards/ceph:Z
        user: '${HOST_USER:-1000}'
        environment:
            - GF_INSTALL_PLUGINS=grafana-piechart-panel 1.4.0,vonage-status-panel 1.0.9

    prometheus:
        image: ${PROMETHEUS_IMAGE:-prom/prometheus:v2.7.2}
        container_name: prometheus
        hostname: prometheus
        ports: ['${PROMETHEUS_HOST_PORT:-9090}:9090']
        volumes:
            - ./docker/prometheus:/etc/prometheus:Z
            - ${CEPH_REPO_DIR}/monitoring/prometheus/alerts:/etc/prometheus/alerts:Z
        user: '${HOST_USER:-1000}'

    node-exporter:
        image: ${NODE_EXPORTER_IMAGE:-prom/node-exporter:v0.17.0}
        container_name: node-exporter
        hostname: node-exporter
        ports: ['${NODE_EXPORTER_HOST_PORT:-9100}:9100']
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--no-collector.timex'

    alertmanager:
        image: ${ALERTMANAGER_IMAGE:-prom/alertmanager:v0.16.2}
        container_name: alertmanager
        hostname: alertmanager
        ports: ['${ALERTMANAGER_HOST_PORT:-9093}:9093']
        volumes:
            - ./docker/alertmanager:/etc/alertmanager:Z
        user: '${HOST_USER:-1000}'
        command:
            - '--config.file=/etc/alertmanager/config.yml'

    keycloak:
        image: jboss/keycloak:4.8.3.Final
        container_name: keycloak
        hostname: keycloak
        ports: ['${KEYCLOAK_HOST_PORT:-8080}:8080']
        volumes:
            - ./docker/keycloak:/docker:Z
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=keycloak
        command: -b 0.0.0.0 -Dkeycloak.import=/docker/saml-demo-realm.json
        scale: -1

volumes:
    empty_volume:
    grafana_data:

networks:
    default:
        driver: bridge
        enable_ipv6: true
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24
                - subnet: 2600:3c02:e000:0058::/64
