route:
  receiver: 'default'
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  routes:
    - match:
        instance: "ceph:9283"
      receiver: 'ceph'
    - match:
        instance: "ceph2:9283"
      receiver: 'ceph2'

receivers:
  - name: 'default'
  - name: 'ceph'
    webhook_configs:
    - url: 'http://ceph:11000/api/prometheus_receiver'
  - name: 'ceph2'
    webhook_configs:
    - url: 'http://ceph2:11000/api/prometheus_receiver'
