name: Publish ceph images

on:
  push:
    branches: 
      - master
    paths:
    - .github/workflows/main.yml
    - docker/ceph/aws/aws-cli-configure.sh
    - docker/ceph/centos/Dockerfile
    - docker/ceph/master/Dockerfile
    - docker/ceph/nautilus/Dockerfile
    - docker/ceph/octopus/Dockerfile
    - docker/ceph/rpm/master/Dockerfile
    - docker/ceph/rpm/nautilus/Dockerfile
    - docker/ceph/rpm/octopus/Dockerfile
    - docker/ceph/rpm/set-ceph-repo.sh
  pull_request:
    branches:
      - master
    paths:
    - .github/workflows/main.yml
    - docker/ceph/aws/aws-cli-configure.sh
    - docker/ceph/centos/Dockerfile
    - docker/ceph/master/Dockerfile
    - docker/ceph/nautilus/Dockerfile
    - docker/ceph/octopus/Dockerfile
    - docker/ceph/rpm/master/Dockerfile
    - docker/ceph/rpm/nautilus/Dockerfile
    - docker/ceph/rpm/octopus/Dockerfile
    - docker/ceph/rpm/set-ceph-repo.sh
  schedule:
    - cron:  '0 2 * * *'

jobs:
  build-ceph-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [centos8]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: docker build -t docker.io/rhcsdashboard/ceph-base:${{ matrix.os }} -f docker/ceph/centos/Dockerfile ./docker/ceph
    - name: Push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push docker.io/rhcsdashboard/ceph-base:${{ matrix.os }}
        docker logout
  build-ceph:
    needs: build-ceph-base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, octopus, nautilus]
        name: [ceph, ceph-rpm]
        include:
          - name: ceph
            dir: ceph
          - name: ceph-rpm
            dir: ceph/rpm
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: docker build -t docker.io/rhcsdashboard/${{ matrix.name }}:${{ matrix.branch }} -f docker/${{ matrix.dir }}/${{ matrix.branch }}/Dockerfile ./docker/ceph
    - name: Push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push docker.io/rhcsdashboard/${{ matrix.name }}:${{ matrix.branch }}
        docker logout
